name: TNBC Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Verify PowerShell
        run: pwsh -v
        shell: bash

      - name: Run pipeline (PowerShell)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          .\scripts\run_all.ps1 -Root "$PWD"

      - name: Collect release assets
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $Rep = Join-Path $PWD "results\REPORTS"
          if (!(Test-Path $Rep)) { New-Item -ItemType Directory -Force -Path $Rep | Out-Null }
          Write-Host "Listing assets:"
          Get-ChildItem $Rep | Format-Table -AutoSize
          Get-ChildItem "$PWD\results\m3" | Format-Table -AutoSize

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            results/REPORTS/checksums_M3.sha256
            results/REPORTS/release_manifest_M3.tsv
            results/m3/TNBC_master_bundle.zip
            results/m3/TNBC_repro_bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
