name: TNBC Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write    # <-- needed to create releases

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        shell: pwsh
        run: |
          Write-Host "PWD: $PWD"
          Get-ChildItem -Force | Format-Table -AutoSize
          if (Test-Path .\results) { Get-ChildItem -Recurse -Force .\results | Select-Object -First 50 | Format-Table -AutoSize }

      - name: Run pipeline (PowerShell, tee log)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $log = Join-Path $PWD 'results\REPORTS\ci_run_log.txt'
          if (!(Test-Path (Split-Path $log))) { New-Item -ItemType Directory -Force -Path (Split-Path $log) | Out-Null }
          .\scripts\run_all.ps1 -Root "$PWD" *>&1 | Tee-Object -FilePath $log
          if (Test-Path 'results\REPORTS\release_manifest_M3.tsv') { exit 0 } else { exit 1 }

      - name: List outputs
        if: always()
        shell: pwsh
        run: |
          Write-Host "`n--- REPORTS ---"
          if (Test-Path .\results\REPORTS) { Get-ChildItem .\results\REPORTS -Force | Format-Table -AutoSize } else { Write-Host "missing: results\REPORTS" }
          Write-Host "`n--- m3 ---"
          if (Test-Path .\results\m3) { Get-ChildItem .\results\m3 -Force | Format-Table -AutoSize } else { Write-Host "missing: results\m3" }

      - name: Upload CI artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tnbc-build-${{ github.run_id }}
          path: |
            results/REPORTS/**
            results/m3/**
          if-no-files-found: warn
          retention-days: 7

      # Create a GitHub Release when running on a tag
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}   # <-- use your PAT secret
          files: |
            results/REPORTS/checksums_M3.sha256
            results/REPORTS/release_manifest_M3.tsv
            results/m3/TNBC_master_bundle.zip
            results/m3/TNBC_repro_bundle.zip
