name: TNBC Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Quick visibility into what the runner sees
      - name: Show tree
        shell: pwsh
        run: |
          Write-Host "PWD: $PWD"
          Get-ChildItem -Force
          if (Test-Path .\results) { Get-ChildItem -Recurse -Force .\results | Select-Object -First 50 | Format-Table -AutoSize }

      # Run our PowerShell pipeline runner (it handles 'no R' gracefully)
      - name: Run pipeline (PowerShell)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          .\scripts\run_all.ps1 -Root "$PWD"

      - name: List outputs
        shell: pwsh
        run: |
          Write-Host "`n--- REPORTS ---"
          if (Test-Path .\results\REPORTS) { Get-ChildItem .\results\REPORTS -Force | Format-Table -AutoSize } else { Write-Host "missing: results\REPORTS" }
          Write-Host "`n--- m3 ---"
          if (Test-Path .\results\m3) { Get-ChildItem .\results\m3 -Force | Format-Table -AutoSize } else { Write-Host "missing: results\m3" }

      # Always upload build artifacts for inspection (even if release step is skipped)
      - name: Upload CI artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tnbc-build-${{ github.run_id }}
          path: |
            results/REPORTS/**
            results/m3/**
          if-no-files-found: warn
          retention-days: 7

      # Only create a GitHub Release on a tag
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            results/REPORTS/checksums_M3.sha256
            results/REPORTS/release_manifest_M3.tsv
            results/m3/TNBC_master_bundle.zip
            results/m3/TNBC_repro_bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
